In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer # Para convertir texto en una matriz de conteo de palabras

In [3]:
# Dataset de ejemplo para clasificación de spam
emails = [
    "Oferta barata, gana dinero",
    "Proyecto pendiente de trabajo",
    "Oferta especial gratis",
    "Reunión de equipo mañana",
    "Gana premios y dinero ahora",
    "Informe mensual adjunto",
    "Oferta gratis y premios",
    "Reporte trimestral listo",
    "Gana dinero fácil ahora",
    "Agenda de la reunión",
    "Premio gratis para ti",
    "Proyecto finalizado exitosamente",
    "Oferta exclusiva barata",
    "Calendario de entregas",
    "Dinero rápido y fácil"
]

labels = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]  # 1=Spam, 0=No Spam

In [11]:
# Convertir texto en una matriz de conteo de palabras (bag-of-words)
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)
print(X.toarray())  # Matriz de características

[[0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 

In [ ]:
print("Vocabulario:", vectorizer.get_feature_names_out()) # Mostrar las características (palabras)

Vocabulario: ['adjunto' 'agenda' 'ahora' 'barata' 'calendario' 'de' 'dinero' 'entregas'
 'equipo' 'especial' 'exclusiva' 'exitosamente' 'finalizado' 'fácil'
 'gana' 'gratis' 'informe' 'la' 'listo' 'mañana' 'mensual' 'oferta' 'para'
 'pendiente' 'premio' 'premios' 'proyecto' 'reporte' 'reunión' 'rápido'
 'ti' 'trabajo' 'trimestral']


In [9]:
print("Forma de la matriz de características:", X.shape)  # (n_samples, n_features)

Forma de la matriz de características: (15, 33)


In [10]:
# Ejemplo del primer mail
print("Vectorizado:", X.toarray()[0])

Vectorizado: [0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]


In [12]:
# Dividir el dataset en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.3, random_state=42)

In [13]:
# Entrenar el modelo Naive Bayes
model = MultinomialNB(alpha=1.0) # Suavizado de Laplace
model.fit(X_train, y_train) # Entrenamiento del modelo
# Hacer predicciones
y_pred = model.predict(X_test)
# Evaluar el modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo:", accuracy)
print("Reporte de clasificación:\n", classification_report(y_test, y_pred))
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred))

Precisión del modelo: 0.8
Reporte de clasificación:
               precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.50      1.00      0.67         1

    accuracy                           0.80         5
   macro avg       0.75      0.88      0.76         5
weighted avg       0.90      0.80      0.82         5

Matriz de confusión:
 [[3 1]
 [0 1]]


In [22]:
# Probar el modelo con un nuevo email
new_email = ["compra Viagra barato ahora"]
new_email_vectorized = vectorizer.transform(new_email)
prediction = model.predict(new_email_vectorized)
print("Predicción para el nuevo email:", prediction)  # 1=Spam, 0=No Spam
probabilities = model.predict_proba(new_email_vectorized)
print("Probabilidades de clase para el nuevo email:", probabilities)  # Probabilidades para cada clase

Predicción para el nuevo email: [1]
Probabilidades de clase para el nuevo email: [[0.15616438 0.84383562]]


In [21]:
# Mostrar las probabilidades de cada característica para cada clase (palabra)
features_names = vectorizer.get_feature_names_out() # Obtener nombres de características
feature_log_prob = model.feature_log_prob_ # Probabilidades logarítmicas de cada característica para cada clase
print("Probabilidades logarítmicas de cada característica para cada clase:\n", feature_log_prob)
spam_probs = np.exp(feature_log_prob[1])  # Probabilidades para la clase spam
top_spam_indices = np.argsort(spam_probs)[-5:][::-1] # Índices de las 5 características más indicativas de spam
print("Características más indicativas de spam:")
for idx in top_spam_indices:
    print(f"  {features_names[idx]}: {spam_probs[idx]:.4f}")

Probabilidades logarítmicas de cada característica para cada clase:
 [[-3.78418963 -3.78418963 -3.78418963 -3.78418963 -3.78418963 -2.68557735
  -3.78418963 -3.78418963 -3.09104245 -3.78418963 -3.78418963 -3.78418963
  -3.78418963 -3.78418963 -3.78418963 -3.78418963 -3.78418963 -3.78418963
  -3.09104245 -3.09104245 -3.78418963 -3.78418963 -3.78418963 -3.09104245
  -3.78418963 -3.78418963 -3.09104245 -3.09104245 -3.09104245 -3.78418963
  -3.78418963 -3.09104245 -3.09104245]
 [-4.04305127 -4.04305127 -2.94443898 -3.34990409 -4.04305127 -4.04305127
  -2.65675691 -4.04305127 -4.04305127 -3.34990409 -3.34990409 -4.04305127
  -4.04305127 -2.94443898 -2.94443898 -2.65675691 -4.04305127 -4.04305127
  -4.04305127 -4.04305127 -4.04305127 -2.65675691 -3.34990409 -4.04305127
  -3.34990409 -2.94443898 -4.04305127 -4.04305127 -4.04305127 -3.34990409
  -3.34990409 -4.04305127 -4.04305127]]
Características más indicativas de spam:
  oferta: 0.0702
  gratis: 0.0702
  dinero: 0.0702
  fácil: 0.0526
  ga