## 1. Ejemplos básicos Numpy

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr3 = arr1 # no crea otro array, solo una referencia
arr4 = arr1.copy() # crea una copia del array
print(id(arr1), id(arr3), id(arr4)) # id() muestra la dirección de memoria

1861201745392 1861201745392 1860827549104


In [6]:
np.arange(10) # array con valores del 0 al 9
np.arange(2, 10) # array con valores del 2 al 9

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Listas en python
mi_lista = [1, 2, 3, 4, 5]
mi_lista2 = [6, 7, 8, 9, 10]
suma_listas = [x + y for x, y in zip(mi_lista, mi_lista2)]
print(suma_listas)

# Suma de arrays en numpy
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
suma_arrays = arr1 + arr2  # sintaxis más sencilla y eficiente
print(suma_arrays)
array_suma_5 = arr1 + 5  # suma 5 a cada elemento del array (Broadcasting)
print(array_suma_5)

[7, 9, 11, 13, 15]
[ 7  9 11 13 15]
[ 6  7  8  9 10]


#### función numpy.linspace()

In [9]:
np.linspace(0, 1, 5)  # array con 5 valores equiespaciados entre 0 y 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.linspace(0, 1, 5, endpoint=False)  # array con 5 valores equiespaciados entre 0 y 1

array([0. , 0.2, 0.4, 0.6, 0.8])

#### numpy.zeros() y numpy.ones()

In [15]:
np.zeros(5)  # array de 5 ceros
np.ones(5)   # array de 5 unos
np.zeros((3, 4))  # matriz de 3x4 de ceros
np.zeros((3,4), dtype='int64')  # matriz de 3x4 de ceros enteros con tipo de dato int64

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

#### Tipos de datos

In [18]:
arr1 = np.array([1, 1.57, True, True, False])
arr1

array([1.  , 1.57, 1.  , 1.  , 0.  ])

In [19]:
arr2 = np.array([111, 2.5, 'python', 'abc'])
arr2

array(['111', '2.5', 'python', 'abc'], dtype='<U32')

In [20]:
arr3 = np.array([111,'python', 'abc'])
arr3

array(['111', 'python', 'abc'], dtype='<U11')

#### Indexación y slicing

In [21]:
a = np.array([0, 1, 2, 3, 4, 5])
a[-1]

5

In [22]:
a[1:3]

array([1, 2])

In [24]:
bidimensional = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bidimensional[1, 2]  # elemento en la fila 1, columna
bidimensional[1][2]  # otra forma de acceder al mismo elemento
bidimensional[:2]  # queda las dos primeras filas

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
bidimensional[1:,1:]  # submatriz desde la fila 1 y columna 1

array([[5, 6],
       [8, 9]])

#### Indexación Fancy

In [ ]:
arr100 = np.arange(100)
arr_multiplos_5 = (arr100 % 5 == 0) # máscara booleana para múltiplos de 5 (filtro)
arr100[arr_multiplos_5]  # filtra los múltiplos de 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [32]:
arr2 = arr100[(arr100 % 5 == 0) & (arr100 % 3 == 0) & (arr100 > 0)]  # forma compacta de hacer lo mismo
arr2

array([15, 30, 45, 60, 75, 90])

#### Atributos y Shaping (organización-dimensiones)

In [33]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape  # devuelve una tupla con las dimensiones del array (filas, columnas)

(2, 3)

In [34]:
a.size

6

In [35]:
a.ndim

2

In [40]:
a = np.arange(15).reshape(3, 5)  # cambia la forma del array 1D a 2D (3 filas, 5 columnas)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
a[0] = 10  # asigna el valor 10 a toda la primera fila
a

array([[10, 10, 10, 10, 10],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:

b = a.reshape(5, 3)  # cambia la forma del array a 5 filas y 3 columnas
b

array([[10, 10, 10],
       [10, 10,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [43]:
c = a.T  # otra forma de obtener la matriz transpuesta
c

array([[10,  5, 10],
       [10,  6, 11],
       [10,  7, 12],
       [10,  8, 13],
       [10,  9, 14]])

In [46]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.append(a, [[7, 8, 9]], axis=0)  # añade una fila al final
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
c = np.append(a, [[10], [11]], axis=1)  # añade una columna al final
c

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.delete(a, 0, axis=0)  # elimina la primera fila

array([[4, 5, 6]])