## Operaciones con Arrays en Numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a*3

array([3, 6, 9])

In [4]:
a+a

array([2, 4, 6])

In [5]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [6]:
a = np.arange(10) # 0..9
raiz_a = np.sqrt(a)
raiz_a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
exp_a = np.exp(a)
exp_a

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
np.random.seed(123) # fijar la semilla
a = np.random.randint(1,1000,100)
a

array([511, 366, 383, 323, 989,  99, 743,  18, 596, 107, 124, 570, 215,
       738,  97, 114, 639,  48,  74, 545, 943, 225, 112, 410, 340, 847,
       254, 421, 609, 209,  69, 818, 824, 452,   3, 341,  40, 323, 597,
       560, 505, 958, 177, 136, 874, 100, 381, 861, 181, 359, 866, 214,
       631, 863, 412, 291, 994, 589, 681, 900, 107, 838, 577, 844, 419,
       827, 395, 791, 718, 147, 485, 272, 412, 766, 159, 181, 583, 366,
       372, 155, 721, 391, 783, 256, 245, 360, 972, 951, 968, 130, 556,
       187, 358, 696, 538, 435, 981, 825, 306, 781])

In [9]:
np.unique(a)

array([  3,  18,  40,  48,  69,  74,  97,  99, 100, 107, 112, 114, 124,
       130, 136, 147, 155, 159, 177, 181, 187, 209, 214, 215, 225, 245,
       254, 256, 272, 291, 306, 323, 340, 341, 358, 359, 360, 366, 372,
       381, 383, 391, 395, 410, 412, 419, 421, 435, 452, 485, 505, 511,
       538, 545, 556, 560, 570, 577, 583, 589, 596, 597, 609, 631, 639,
       681, 696, 718, 721, 738, 743, 766, 781, 783, 791, 818, 824, 825,
       827, 838, 844, 847, 861, 863, 866, 874, 900, 943, 951, 958, 968,
       972, 981, 989, 994])

In [10]:
b = np.array([1,1,2,3,5,4])
print(b.mean())
print(np.mean(b))
print(np.median(b))
print(np.sum(b))
print(np.round(np.var(b),2))
print(np.max(b))
print(np.min(b))
print(np.argmax(b))
print(b.std())

2.6666666666666665
2.6666666666666665
2.5
16
2.22
5
1
4
1.49071198499986


In [11]:
y = np.arange(1,10) # 1..9
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y = y.reshape(3,-1) # 3 filas, columnas automáticas
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(y.mean(axis=0)) # media por columnas
print(y.mean(axis=1)) # media por filas
print(y.max(axis=0)) # max por columnas
print(y.max(axis=1)) # max por filas

[4. 5. 6.]
[2. 5. 8.]
[7 8 9]
[3 6 9]


In [15]:
(y>5).sum()  # cuántos elementos son mayores que 5

4

In [16]:
desordenar = np.array([3,1,4,2,5,1])
np.sort(desordenar)

array([1, 1, 2, 3, 4, 5])

In [ ]:
sorted_desordenar = sorted(set(desordenar)) # lista ordenada sin duplicados de un array
sorted_desordenar

[1, 2, 3, 4, 5]

In [18]:
numeros_desordenados = np.array([10,2,8,4,6,2,4,8,10])
test_a = numeros_desordenados > 3
test_a

array([ True, False,  True,  True,  True, False,  True,  True,  True])

In [19]:
a = np.arange(15).reshape(3, 5) # 3 filas, 5 columnas
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [21]:
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [22]:
arr = np.random.randn(4,3) # 4 filas, 3 columnas
arr

array([[ 0.37085233,  1.17430715, -2.03229248],
       [ 0.58250829, -0.7211758 , -1.7024236 ],
       [ 0.76764147,  0.37067905,  2.07545935],
       [ 0.12775769,  1.79988945,  1.23836635]])

In [24]:
# multiplicación de matrices
np.dot(a.T, a)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [25]:
# Matrices tridimensionales
b = np.arange(24).reshape(2,3,4) # 2 bloques, 3 filas, 4 columnas
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
b.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [ ]:
sueldos = np.array((1000, 1200, 1100, 1050, 1150)) # sueldos de 5 meses
np.cumsum(sueldos) # sueldos acumulados

array([1000, 2200, 3300, 4350, 5500])